/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouteRouteImport } from './routes/route'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdIndexRouteImport } from './routes/$userId/index'
import { Route as UserIdEditRouteImport } from './routes/$userId/edit'

const RouteRoute = RouteRouteImport.update({
  id: '',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/$userId/',
  path: '/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdEditRoute = UserIdEditRouteImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/$userId/edit': typeof UserIdEditRoute
  '/$userId': typeof UserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/$userId/edit': typeof UserIdEditRoute
  '/$userId': typeof UserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '': typeof RouteRoute
  '/new': typeof NewRoute
  '/$userId/edit': typeof UserIdEditRoute
  '/$userId/': typeof UserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/$userId/edit' | '/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/$userId/edit' | '/$userId'
  id: '__root__' | '/' | '' | '/new' | '/$userId/edit' | '/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RouteRoute: typeof RouteRoute
  NewRoute: typeof NewRoute
  UserIdEditRoute: typeof UserIdEditRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '': {
      id: ''
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/': {
      id: '/$userId/'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/edit': {
      id: '/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/$userId/edit'
      preLoaderRoute: typeof UserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RouteRoute: RouteRoute,
  NewRoute: NewRoute,
  UserIdEditRoute: UserIdEditRoute,
  UserIdIndexRoute: UserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
